const quizgenerator = {
    tooltitle: ".tool-title",
    topicorblueprint: "//span[normalize-space()='Topic or Blueprint']",
    selecttopic: ".multiselect__tags",
    selecttopicinput: "#single-select-object",
    topicoption: "ul.multiselect__content li.multiselect__element span.multiselect__option span",
    gradelevel:"//label[normalize-space()='Select Grade Level'] ",
    gradeoption: ".grade-level-icon",
    blueprintsummary: "div[class='workflow-card readonly-card'] div[class='workflow-card-header']",
    topic:"(//div[@class='attribute-header'])[1]",
    topicvalue: ".attribute-value",
    transcriptcontent: "//textarea[@id='transcript']",
    wordcount: "//div[@class='stat-item-container']//div[1]",
    readingtime: "//div[@class='stat-item-container']//div[2]",
    learningstandard: "#standards",
    gradingprogression: "textarea[placeholder='E.g. For Grade 5, include basic comprehension questions; for Grade 8, emphasize analytical thinking and require justification of answers...']",
    conceptsquiz: "div[class='quiz-type-card selected'] h4[class='quiz-type-name']",
    conceptsquizbutton:"#quiz-type-concepts",
    misconceptquiz: "div[class='quiz-type-card'] h4[class='quiz-type-name']",
    misconceptquizbutton: "#quiz-type-misconceptions",
    multiplechoice:"//h4[normalize-space()='Multiple Choice']",
    multiplechoicebutton:"#type-multiple-choice",
    multiselect:"//h4[normalize-space()='Multi Select']",
    multiselectbutton:"#type-multi-select",
    fillinthetable:"//h4[normalize-space()='Fill in the Table']",
    fillinthetablebutton:"#type-fill-table",
    matchlist:"//h4[normalize-space()='Match List']",
    matchlistbutton:"#type-match-list",
    venndiagram:"//h4[normalize-space()='Venn Diagram']",
    venndiagrambutton:"#type-venn-diagram",
    fillinthesentence:"#type-fill-sentence",
    additionalinstruction:"textarea[placeholder='Type your instructions here...']",
    providerSelect: 'select.form-select >> nth=0',
    modelSelect: 'select.form-select >> nth=1',
    generatequestion:"//button[normalize-space()='Generate Questions']",
    questioncard:"(//div[@class='question-card'])",
    questioncardtitle:"div[class$='footer-badges']",
    gradeappropriate:"(//div[@class='criterion-header'])[1]",
    gradeappropriatevalue:"(//input[@placeholder='Add a comment'])[1]",
    independentcompletionwithmovieonly: "(//div[@class='criterion-header'])[2]",
    independentcompletionwithmovieonlyvalue: "(//input[@placeholder='Add a comment'])[2]",
    contentfocus:"(//div[@class='criterion-header'])[3]",
    contentfocusvalue:"(//input[@placeholder='Add a comment'])[3]", 
    vocabularyintegration: "(//div[@class='criterion-header'])[4]",
    vocabularyintegrationvalue: "(//input[@placeholder='Add a comment'])[4]",
    answerformatting: "(//div[@class='criterion-header'])[5]",
    answerformattingvalue: "(//input[@placeholder='Add a comment'])[5]",
    distractorquality: "(//div[@class='criterion-header'])[6]",
    distractorqualityvalue: "(//input[@placeholder='Add a comment'])[6]",   
    imagesuggestion: "(//div[@class='criterion-header'])[7]",
    imagesuggestionvalue: "(//input[@placeholder='Add a comment'])[7]",
    plainlanguage: "(//div[@class='criterion-header'])[8]",
    plainlanguagevalue: "(//input[@placeholder='Add a comment'])[8]",
    punctuationandformatting: "(//div[@class='criterion-header'])[9]",
    punctuationandformattingvalue: "(//input[@placeholder='Add a comment'])[9]",
    reset:"(//button[contains(text(),'Reset')])[3]",
    gradeleveltext:"//p[normalize-space()='Select a topic to view grade details.']",
    blueprintsummarytext: "//p[normalize-space()='Select a topic to view blueprint details']",
    generatequestiontext:"body > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > main:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(5) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > p:nth-child(3)"

    
}

export default { quizgenerator };